### ISSUE TITLE
Unknown magical property: 25

### ISSUE THREAD

**Issue by opennota** [nokka/d2s#1]
While parsing some .d2s files from here
http://www.dethguild.com/diablo/diablo-character-packs/
e.g.
Level 99 Bone Necromancer
http://www.dethguild.com/wp-content/uploads/files/diablo/SilverDeth.d2s
I get errors like
Char name: SilverDeth, error that occurred: Unknown magical property: 25

**Comment by nokka** [comment]
Hi, thanks for bringing this up, I've reverse engineered all these magical properties by hand, so I might have missed some. I thought I had done them all by now. But you're right, 25 seems to be missing. https://github.com/nokka/d2s/blob/master/item.go#L554

I'll have a look tonight. What version are the characters you're parsing? The binary layout differs a bit from different versions, and I wrote this on 1.10+ basically.

**Comment by opennota** [comment]
No idea about version. Some other .d2s files from the web page were parsed successfully.

**Comment by kambala-decapitator** [comment]
> I've reverse engineered all these magical properties by hand

but why?.. All info is well-known for cLoD: 
https://d2mods.info/forum/kb/index?c=4, and source txts are freely available in the mpq(s).
