### ISSUE TITLE
New magic property

### ISSUE THREAD

**Issue by artcom-net** [nokka/d2s#8]
Hi there!
When I wrote an implementation for Python, I discovered something missing a magic property, it is with ID = 49 and is called '{} to Maximum Fire Damage' (Cathan's Rule). Sorry for my bad english (maybe). Pull request: https://github.com/nokka/d2s/pull/7

**Comment by squeek502** [comment]
You're right, that ID can be used on its own (most of the time its combined with ID 48).

This same thing is also technically true for ID 51 (`+{0} to Maximum Lightning Damage`), ID 53 (`+{0} to Maximum Magic Damage`), ID 55 (`+{0} to Maximum Cold Damage`) and probably poision, too, but that follows a slightly different pattern I think. Not sure if any items use ID 51/53/55 in normal D2 though.

**Comment by artcom-net** [comment]
I found only one item that has a similar property (+ x to max `elemental` damage). I did't find others with a similar one.

**Comment by nokka** [comment]
Thanks so much for this, I appreciate it! It has been merged, I'll close the issue.
